[package]
name = "xdiff"
version = "0.3.0"
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/xdiff"
repository = "https://github.com/Tubitv/xdiff"
homepage = "https://github.com/Tubitv/xdiff"
description = """
xdiff CLI
"""
readme = "../README.md"
keywords = ["cli", "diff"]
categories = ["development-tools"]

[dependencies]
anyhow = "1.0.62"
clap = { version = "3.2.17", features = ["derive"] }
tokio = { version = "1.20.1", features = ["full"] }
serde_json = "1.0.85"

xreq-cli-utils = { version = "0.2.0", path = "../cli-utils" }
xreq-lib = { version = "0.3.1", path = "../requester" }
